<a href="https://colab.research.google.com/github/BerkeEkingen/BerkeEkingen/blob/main/BerkeEk%C4%B1ngenlab1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np

arr1 = np.arange(1, 11)
print(arr1)



[ 1  2  3  4  5  6  7  8  9 10]


In [3]:
arr2 = arr1.astype(np.float32)
print(arr2)

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]


In [4]:
arr3 = 2 ** np.arange(2, 17)
print(arr3)


[    4     8    16    32    64   128   256   512  1024  2048  4096  8192
 16384 32768 65536]


In [5]:
arr4 = np.arange(1, 26).reshape(5, 5)

print(arr4)
print("\nLast value:")
print(arr4[-1, -1])

print("\nSecond column:")
print(arr4[:, 1])

print("\nThird row:")
print(arr4[2, :])

print("\nMain diagonal:")
print(np.diag(arr4))

print("\nValues 9,10,14,15:")
print(arr4[1:3, 3:5])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]

Last value:
25

Second column:
[ 2  7 12 17 22]

Third row:
[11 12 13 14 15]

Main diagonal:
[ 1  7 13 19 25]

Values 9,10,14,15:
[[ 9 10]
 [14 15]]


In [6]:
arr5 = np.arange(1, 28).reshape(3, 3, 3)

print("Original array:")
print(arr5)

print("\ny = 1:")
print(arr5[:, 1, :])

print("\nz = 1 and z = 3:")
print(arr5[:, :, [0, 2]])


Original array:
[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]
  [25 26 27]]]

y = 1:
[[ 4  5  6]
 [13 14 15]
 [22 23 24]]

z = 1 and z = 3:
[[[ 1  3]
  [ 4  6]
  [ 7  9]]

 [[10 12]
  [13 15]
  [16 18]]

 [[19 21]
  [22 24]
  [25 27]]]


In [7]:
import time
import numpy as np

my_list = list(range(10000))

start = time.time()
result = []
for x in my_list:
    result.append(x * 2)
print("For loop:", time.time() - start)

start = time.time()
result = [x * 2 for x in my_list]
print("List comprehension:", time.time() - start)

np_array = np.arange(10000)

start = time.time()
result = np_array * 2
print("NumPy:", time.time() - start)

For loop: 0.001508474349975586
List comprehension: 0.0009138584136962891
NumPy: 0.0005102157592773438
