<a href="https://colab.research.google.com/github/BerkeEkingen/BerkeEkingen/blob/main/BerkeEk%C4%B1ngenlab3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [13]:
import numpy as np

a_small_one = np.arange(1, 65).reshape(8, 8)

print(a_small_one)

[[ 1  2  3  4  5  6  7  8]
 [ 9 10 11 12 13 14 15 16]
 [17 18 19 20 21 22 23 24]
 [25 26 27 28 29 30 31 32]
 [33 34 35 36 37 38 39 40]
 [41 42 43 44 45 46 47 48]
 [49 50 51 52 53 54 55 56]
 [57 58 59 60 61 62 63 64]]


In [14]:
print("Sum of each column:")
print(np.sum(a_small_one, axis=0))

print("\nCumulative sum for each row:")
print(np.cumsum(a_small_one, axis=1))

print("\nAverage value for each row:")
print(np.mean(a_small_one, axis=1))

Sum of each column:
[232 240 248 256 264 272 280 288]

Cumulative sum for each row:
[[  1   3   6  10  15  21  28  36]
 [  9  19  30  42  55  69  84 100]
 [ 17  35  54  74  95 117 140 164]
 [ 25  51  78 106 135 165 196 228]
 [ 33  67 102 138 175 213 252 292]
 [ 41  83 126 170 215 261 308 356]
 [ 49  99 150 202 255 309 364 420]
 [ 57 115 174 234 295 357 420 484]]

Average value for each row:
[ 4.5 12.5 20.5 28.5 36.5 44.5 52.5 60.5]


In [15]:
even_elements = a_small_one[a_small_one % 2 == 0]

print(even_elements)

[ 2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48
 50 52 54 56 58 60 62 64]


In [16]:
no_even_small_one = a_small_one.astype(float).copy()

no_even_small_one[no_even_small_one % 2 == 0] = np.nan

print(no_even_small_one)

[[ 1. nan  3. nan  5. nan  7. nan]
 [ 9. nan 11. nan 13. nan 15. nan]
 [17. nan 19. nan 21. nan 23. nan]
 [25. nan 27. nan 29. nan 31. nan]
 [33. nan 35. nan 37. nan 39. nan]
 [41. nan 43. nan 45. nan 47. nan]
 [49. nan 51. nan 53. nan 55. nan]
 [57. nan 59. nan 61. nan 63. nan]]


In [17]:
print("Sum for each row:")
print(np.nansum(no_even_small_one, axis=1))

print("\nAverage for each column:")
print(np.nanmean(no_even_small_one, axis=0))

print("\nSmallest value:")
print(np.nanmin(no_even_small_one))

Sum for each row:
[ 16.  48.  80. 112. 144. 176. 208. 240.]

Average for each column:
[29. nan 31. nan 33. nan 35. nan]

Smallest value:
1.0


/tmp/ipykernel_2830/3568288267.py:5: RuntimeWarning: Mean of empty slice
  print(np.nanmean(no_even_small_one, axis=0))


In [18]:
restored_array = np.where(
    np.isnan(no_even_small_one),
    a_small_one,
    no_even_small_one
)

print(restored_array)

[[ 1.  2.  3.  4.  5.  6.  7.  8.]
 [ 9. 10. 11. 12. 13. 14. 15. 16.]
 [17. 18. 19. 20. 21. 22. 23. 24.]
 [25. 26. 27. 28. 29. 30. 31. 32.]
 [33. 34. 35. 36. 37. 38. 39. 40.]
 [41. 42. 43. 44. 45. 46. 47. 48.]
 [49. 50. 51. 52. 53. 54. 55. 56.]
 [57. 58. 59. 60. 61. 62. 63. 64.]]


In [19]:
normal_100 = np.random.normal(
    loc=0,
    scale=1,
    size=(100, 100)
)

print(normal_100)

[[-0.86029672 -0.42341072 -0.6894303  ... -0.11679775  0.62623215
  -1.01974113]
 [-2.28358968  0.78637512 -0.1284242  ... -0.24279214 -1.86188967
  -0.72957714]
 [ 0.23735656 -0.11463325  0.10823752 ...  1.30049031 -0.45093491
   0.24619379]
 ...
 [-2.51530791  0.87977205  1.87059863 ...  1.63160553  1.47627488
   2.73426658]
 [ 1.10018675  0.98796345 -0.537414   ...  1.70087324  0.08448574
  -0.83203663]
 [ 1.38169802 -0.21064508 -1.32213279 ...  0.81558037  1.07423832
  -1.12499719]]


In [20]:
row_means = np.mean(normal_100, axis=1)
column_means = np.mean(normal_100, axis=0)

print("Row means:")
print(row_means)

print("\nColumn means:")
print(column_means)

row_diff = np.mean(np.abs(row_means))
column_diff = np.mean(np.abs(column_means))

print("\nAverage absolute difference of row means from 0:")
print(row_diff)

print("\nAverage absolute difference of column means from 0:")
print(column_diff)

Row means:
[ 0.03464669 -0.02689134  0.15325218  0.05617378 -0.1931847   0.05089854
 -0.04102621  0.08366351  0.06874766 -0.00222694  0.29980884 -0.09961973
  0.17307439  0.09825765  0.06302991  0.01906587 -0.06593723 -0.11671904
  0.10869759 -0.0046934   0.10867718 -0.16817118  0.04248775  0.05989489
 -0.02234932 -0.05282937  0.01428664 -0.05927296 -0.04221443 -0.0100431
 -0.22098002  0.06633433  0.04978296 -0.04079208  0.02275244  0.11170855
  0.00880117 -0.02976439 -0.05445468 -0.27703332 -0.11815442 -0.1172559
 -0.12069239 -0.05635281  0.01712925  0.03805529  0.01833126  0.08223669
 -0.06273754  0.11232976 -0.10230803 -0.02339116  0.0564642   0.14114773
 -0.02266002 -0.03444629  0.03720209  0.0473601   0.03040594  0.18437283
  0.12182525 -0.02467611  0.0039926   0.02227888  0.02188706  0.12742078
 -0.058599    0.1182013   0.00104291  0.06560003 -0.03014072  0.06907023
  0.02371215 -0.11902307  0.0369001  -0.22601024 -0.10389317 -0.19335156
 -0.03491778 -0.07503821  0.09612605  0.10

In [21]:
import timeit

big_array = np.random.normal(size=(1000, 1000))

In [22]:
txt_time = timeit.timeit(
    lambda: np.savetxt("array.txt", big_array),
    number=1
)

npy_time = timeit.timeit(
    lambda: np.save("array.npy", big_array),
    number=1
)

npz_time = timeit.timeit(
    lambda: np.savez_compressed("array.npz", big_array),
    number=1
)

print("TXT save:", txt_time)
print("NPY save:", npy_time)
print("NPZ save:", npz_time)

TXT save: 2.10581494500002
NPY save: 0.005912269999953423
NPZ save: 0.49023637100003725
