<a href="https://colab.research.google.com/github/BerkeEkingen/BerkeEkingen/blob/main/BerkeEk%C4%B1ngenlab2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [8]:
import numpy as np

arr = np.arange(2, 34, 2).reshape(4, 4)

print("Array:")
print(arr)

print("\nData type:", arr.dtype)
print("Number of elements:", arr.size)
print("Size of one element (bytes):", arr.itemsize)
print("Allocated memory (bytes):", arr.nbytes)

Array:
[[ 2  4  6  8]
 [10 12 14 16]
 [18 20 22 24]
 [26 28 30 32]]

Data type: int64
Number of elements: 16
Size of one element (bytes): 8
Allocated memory (bytes): 128


In [9]:
view_arr = arr.view(np.uint8)

print("View array:")
print(view_arr)

print("\nIs it a view?")
print(view_arr.base is arr)

print("\nData type:", view_arr.dtype)
print("Number of elements:", view_arr.size)
print("Size of one element (bytes):", view_arr.itemsize)
print("Allocated memory (bytes):", view_arr.nbytes)

View array:
[[ 2  0  0  0  0  0  0  0  4  0  0  0  0  0  0  0  6  0  0  0  0  0  0  0
   8  0  0  0  0  0  0  0]
 [10  0  0  0  0  0  0  0 12  0  0  0  0  0  0  0 14  0  0  0  0  0  0  0
  16  0  0  0  0  0  0  0]
 [18  0  0  0  0  0  0  0 20  0  0  0  0  0  0  0 22  0  0  0  0  0  0  0
  24  0  0  0  0  0  0  0]
 [26  0  0  0  0  0  0  0 28  0  0  0  0  0  0  0 30  0  0  0  0  0  0  0
  32  0  0  0  0  0  0  0]]

Is it a view?
False

Data type: uint8
Number of elements: 128
Size of one element (bytes): 1
Allocated memory (bytes): 128


In [10]:
view_center = arr[1:3, 1:3]

copy_center = arr[1:3, 1:3].copy()

print("View:")
print(view_center)

print("\nCopy:")
print(copy_center)

print("\nView base:")
print(view_center.base is arr)

print("Copy base:")
print(copy_center.base is arr)

View:
[[12 14]
 [20 22]]

Copy:
[[12 14]
 [20 22]]

View base:
False
Copy base:
False


In [11]:
arr4 = np.tile(np.arange(1, 5), (4, 1))

mirror = arr4[:, ::-1]

result = np.concatenate((arr4, mirror), axis=1)

print(result)

[[1 2 3 4 4 3 2 1]
 [1 2 3 4 4 3 2 1]
 [1 2 3 4 4 3 2 1]
 [1 2 3 4 4 3 2 1]]


In [12]:
Z_5 = np.ones((2, 2), dtype=int)

Z1 = Z_5 * 1
Z2 = Z_5 * 2
Z3 = Z_5 * 3
Z4 = Z_5 * 4

top = np.concatenate((Z1, Z2), axis=1)
bottom = np.concatenate((Z3, Z4), axis=1)

result = np.concatenate((top, bottom), axis=0)

print(result)

[[1 1 2 2]
 [1 1 2 2]
 [3 3 4 4]
 [3 3 4 4]]
